//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportsOrganizer.UI.Localizations.Settings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReportsOrganizer.UI.Localizations.Settings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ReportsOrginizer with Windows.
        /// </summary>
        internal static string General_AutoRun {
            get {
                return ResourceManager.GetString("General_AutoRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language.
        /// </summary>
        internal static string General_Language {
            get {
                return ResourceManager.GetString("General_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ReportsOrginizer minimized in the system tray.
        /// </summary>
        internal static string General_RunMinimized {
            get {
                return ResourceManager.GetString("General_RunMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Group_General {
            get {
                return ResourceManager.GetString("Group_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        internal static string Group_ManageProjects {
            get {
                return ResourceManager.GetString("Group_ManageProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Group_Notification {
            get {
                return ResourceManager.GetString("Group_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        internal static string Group_Personalization {
            get {
                return ResourceManager.GetString("Group_Personalization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Group_Settings {
            get {
                return ResourceManager.GetString("Group_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project.
        /// </summary>
        internal static string ManageProjects_AddProject {
            get {
                return ResourceManager.GetString("ManageProjects_AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string ManageProjects_FullName {
            get {
                return ResourceManager.GetString("ManageProjects_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string ManageProjects_IsActual {
            get {
                return ResourceManager.GetString("ManageProjects_IsActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an project to edit.
        /// </summary>
        internal static string ManageProjects_SelectProject {
            get {
                return ResourceManager.GetString("ManageProjects_SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short name.
        /// </summary>
        internal static string ManageProjects_ShortName {
            get {
                return ResourceManager.GetString("ManageProjects_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show notification at selected times.
        /// </summary>
        internal static string Notification_IgnoreTime {
            get {
                return ResourceManager.GetString("Notification_IgnoreTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification at intervals.
        /// </summary>
        internal static string Notification_Interval {
            get {
                return ResourceManager.GetString("Notification_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification at selected times.
        /// </summary>
        internal static string Notification_SelectedTime {
            get {
                return ResourceManager.GetString("Notification_SelectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your color theme.
        /// </summary>
        internal static string Personalization_Theme {
            get {
                return ResourceManager.GetString("Personalization_Theme", resourceCulture);
            }
        }
    }
}
